language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq poppler-data poppler-utils python-dev python-imaging python-setuptools python-pdftools python-lxml
  - sudo pip install simplejson
install:
  - pip install -r requirements.txt --timeout 30
# command to run tests, e.g. python setup.py test
script:
  - ./manage.py test
